/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: sanity/schema/schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Socials = {
  _id: string;
  _type: "socials";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  socialLinks?: Array<{
    name: string;
    url: string;
    iconLight: {
      asset: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    iconDark: {
      asset: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    _type: "socialLink";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type BlogsPage = {
  _id: string;
  _type: "blogs-page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  monoLabel: string;
  detailMonoLabel: string;
  title: string;
  description: string;
};

export type AwardsPage = {
  _id: string;
  _type: "awards-page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  monoLabel: string;
  detailMonoLabel: string;
  title: string;
  description: string;
};

export type Skills = {
  _id: string;
  _type: "skills";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  url: string;
  logoLight: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  logoDark: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
};

export type ExperiencesPage = {
  _id: string;
  _type: "experiences-page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  monoLabel: string;
  detailMonoLabel: string;
  title: string;
  description: string;
};

export type ProjectsPage = {
  _id: string;
  _type: "projects-page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  monoLabel: string;
  detailMonoLabel: string;
  title: string;
  description: string;
};

export type ProjectsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "projects";
};

export type ExperiencesReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "experiences";
};

export type AwardsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "awards";
};

export type BlogsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogs";
};

export type SkillsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "skills";
};

export type AboutPage = {
  _id: string;
  _type: "about-page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroMonoLabel: string;
  location: string;
  title: string;
  content: Array<
    | {
        children?: Array<
          | {
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }
          | {
              body: string;
              _type: "latex";
              _key: string;
            }
          | {
              language:
                | "javascript"
                | "jsx"
                | "typescript"
                | "tsx"
                | "go"
                | "html"
                | "css"
                | "php"
                | "java"
                | "ruby"
                | "csharp"
                | "python"
                | "sh"
                | "sql"
                | "mysql"
                | "groq"
                | "text"
                | "markdown"
                | "json"
                | "xml"
                | "yaml";
              code: string;
              _type: "customCode";
              _key: string;
            }
        >;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              reference:
                | ProjectsReference
                | ExperiencesReference
                | AwardsReference
                | BlogsReference;
              _type: "internalLink";
              _key: string;
            }
          | {
              url?: string;
              _type: "externalLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        maxWidth?:
          | "max-w-3xs"
          | "max-w-2xs"
          | "max-w-xs"
          | "max-w-sm"
          | "max-w-md"
          | "max-w-lg"
          | "max-w-xl"
          | "max-w-2xl"
          | "max-w-3xl";
        caption: boolean;
        _type: "image";
        _key: string;
      }
    | {
        body: string;
        _type: "latex";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
    | {
        skills: Array<
          {
            _key: string;
          } & SkillsReference
        >;
        _type: "skillBadges";
        _key: string;
      }
    | {
        contributors: Array<{
          profileUrl: string;
          _type: "contributorProfile";
          _key: string;
        }>;
        _type: "contributors";
        _key: string;
      }
  >;
  image: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  educationMonoLabel: string;
  educationSectionTitle: string;
  educationSectionDescription: string;
  education: Array<{
    image: {
      asset: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    };
    degree: string;
    university: string;
    dateRange: {
      startDate: string;
      endDate?: string;
    };
    description: string;
    _type: "educationItem";
    _key: string;
  }>;
  skillsMonoLabel: string;
  skillsSectionTitle: string;
  skillsSectionDescription: string;
  skillCategories: Array<{
    categoryTitle: string;
    skills: Array<
      {
        _key: string;
      } & SkillsReference
    >;
    _type: "skillCategory";
    _key: string;
  }>;
};

export type Projects = {
  _id: string;
  _type: "projects";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  title: string;
  slug: Slug;
  description: string;
  dateRange: {
    startDate: string;
    endDate?: string;
  };
  repositoryLinks?: Array<{
    label: string;
    url: string;
    _type: "repositoryLink";
    _key: string;
  }>;
  deploymentLinks?: Array<{
    label: string;
    url: string;
    _type: "deploymentLink";
    _key: string;
  }>;
  content: Array<
    | {
        children?: Array<
          | {
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }
          | {
              body: string;
              _type: "latex";
              _key: string;
            }
          | {
              language:
                | "javascript"
                | "jsx"
                | "typescript"
                | "tsx"
                | "go"
                | "html"
                | "css"
                | "php"
                | "java"
                | "ruby"
                | "csharp"
                | "python"
                | "sh"
                | "sql"
                | "mysql"
                | "groq"
                | "text"
                | "markdown"
                | "json"
                | "xml"
                | "yaml";
              code: string;
              _type: "customCode";
              _key: string;
            }
        >;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              reference:
                | ProjectsReference
                | ExperiencesReference
                | AwardsReference
                | BlogsReference;
              _type: "internalLink";
              _key: string;
            }
          | {
              url?: string;
              _type: "externalLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        maxWidth?:
          | "max-w-3xs"
          | "max-w-2xs"
          | "max-w-xs"
          | "max-w-sm"
          | "max-w-md"
          | "max-w-lg"
          | "max-w-xl"
          | "max-w-2xl"
          | "max-w-3xl";
        caption: boolean;
        _type: "image";
        _key: string;
      }
    | {
        body: string;
        _type: "latex";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
    | {
        skills: Array<
          {
            _key: string;
          } & SkillsReference
        >;
        _type: "skillBadges";
        _key: string;
      }
    | {
        contributors: Array<{
          profileUrl: string;
          _type: "contributorProfile";
          _key: string;
        }>;
        _type: "contributors";
        _key: string;
      }
  >;
};

export type CompaniesReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "companies";
};

export type Experiences = {
  _id: string;
  _type: "experiences";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company: CompaniesReference;
  title: string;
  employmentType?: "Contract" | "Part-time" | "Full-time" | "Internship";
  slug: Slug;
  dateRange: {
    startDate: string;
    endDate?: string;
  };
  location?: string;
  repositoryLinks?: Array<{
    label: string;
    url: string;
    _type: "repositoryLink";
    _key: string;
  }>;
  deploymentLinks?: Array<{
    label: string;
    url: string;
    _type: "deploymentLink";
    _key: string;
  }>;
  content: Array<
    | {
        children?: Array<
          | {
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }
          | {
              body: string;
              _type: "latex";
              _key: string;
            }
          | {
              language:
                | "javascript"
                | "jsx"
                | "typescript"
                | "tsx"
                | "go"
                | "html"
                | "css"
                | "php"
                | "java"
                | "ruby"
                | "csharp"
                | "python"
                | "sh"
                | "sql"
                | "mysql"
                | "groq"
                | "text"
                | "markdown"
                | "json"
                | "xml"
                | "yaml";
              code: string;
              _type: "customCode";
              _key: string;
            }
        >;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              reference:
                | ProjectsReference
                | ExperiencesReference
                | AwardsReference
                | BlogsReference;
              _type: "internalLink";
              _key: string;
            }
          | {
              url?: string;
              _type: "externalLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        maxWidth?:
          | "max-w-3xs"
          | "max-w-2xs"
          | "max-w-xs"
          | "max-w-sm"
          | "max-w-md"
          | "max-w-lg"
          | "max-w-xl"
          | "max-w-2xl"
          | "max-w-3xl";
        caption: boolean;
        _type: "image";
        _key: string;
      }
    | {
        body: string;
        _type: "latex";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
    | {
        skills: Array<
          {
            _key: string;
          } & SkillsReference
        >;
        _type: "skillBadges";
        _key: string;
      }
    | {
        contributors: Array<{
          profileUrl: string;
          _type: "contributorProfile";
          _key: string;
        }>;
        _type: "contributors";
        _key: string;
      }
  >;
};

export type Awards = {
  _id: string;
  _type: "awards";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  title: string;
  slug: Slug;
  description: string;
  issuer: string;
  date: string;
  content: Array<
    | {
        children?: Array<
          | {
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }
          | {
              body: string;
              _type: "latex";
              _key: string;
            }
          | {
              language:
                | "javascript"
                | "jsx"
                | "typescript"
                | "tsx"
                | "go"
                | "html"
                | "css"
                | "php"
                | "java"
                | "ruby"
                | "csharp"
                | "python"
                | "sh"
                | "sql"
                | "mysql"
                | "groq"
                | "text"
                | "markdown"
                | "json"
                | "xml"
                | "yaml";
              code: string;
              _type: "customCode";
              _key: string;
            }
        >;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              reference:
                | ProjectsReference
                | ExperiencesReference
                | AwardsReference
                | BlogsReference;
              _type: "internalLink";
              _key: string;
            }
          | {
              url?: string;
              _type: "externalLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        maxWidth?:
          | "max-w-3xs"
          | "max-w-2xs"
          | "max-w-xs"
          | "max-w-sm"
          | "max-w-md"
          | "max-w-lg"
          | "max-w-xl"
          | "max-w-2xl"
          | "max-w-3xl";
        caption: boolean;
        _type: "image";
        _key: string;
      }
    | {
        body: string;
        _type: "latex";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
    | {
        skills: Array<
          {
            _key: string;
          } & SkillsReference
        >;
        _type: "skillBadges";
        _key: string;
      }
    | {
        contributors: Array<{
          profileUrl: string;
          _type: "contributorProfile";
          _key: string;
        }>;
        _type: "contributors";
        _key: string;
      }
  >;
};

export type Blogs = {
  _id: string;
  _type: "blogs";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  title: string;
  slug: Slug;
  description: string;
  date: string;
  content: Array<
    | {
        children?: Array<
          | {
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }
          | {
              body: string;
              _type: "latex";
              _key: string;
            }
          | {
              language:
                | "javascript"
                | "jsx"
                | "typescript"
                | "tsx"
                | "go"
                | "html"
                | "css"
                | "php"
                | "java"
                | "ruby"
                | "csharp"
                | "python"
                | "sh"
                | "sql"
                | "mysql"
                | "groq"
                | "text"
                | "markdown"
                | "json"
                | "xml"
                | "yaml";
              code: string;
              _type: "customCode";
              _key: string;
            }
        >;
        style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<
          | {
              reference:
                | ProjectsReference
                | ExperiencesReference
                | AwardsReference
                | BlogsReference;
              _type: "internalLink";
              _key: string;
            }
          | {
              url?: string;
              _type: "externalLink";
              _key: string;
            }
        >;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        maxWidth?:
          | "max-w-3xs"
          | "max-w-2xs"
          | "max-w-xs"
          | "max-w-sm"
          | "max-w-md"
          | "max-w-lg"
          | "max-w-xl"
          | "max-w-2xl"
          | "max-w-3xl";
        caption: boolean;
        _type: "image";
        _key: string;
      }
    | {
        body: string;
        _type: "latex";
        _key: string;
      }
    | ({
        _key: string;
      } & Code)
    | {
        skills: Array<
          {
            _key: string;
          } & SkillsReference
        >;
        _type: "skillBadges";
        _key: string;
      }
    | {
        contributors: Array<{
          profileUrl: string;
          _type: "contributorProfile";
          _key: string;
        }>;
        _type: "contributors";
        _key: string;
      }
  >;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Companies = {
  _id: string;
  _type: "companies";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image: {
    asset: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  name: string;
  summary: string;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Socials
  | SanityImageCrop
  | SanityImageHotspot
  | BlogsPage
  | AwardsPage
  | Skills
  | ExperiencesPage
  | ProjectsPage
  | ProjectsReference
  | ExperiencesReference
  | AwardsReference
  | BlogsReference
  | SkillsReference
  | AboutPage
  | Projects
  | CompaniesReference
  | Experiences
  | Awards
  | Blogs
  | Slug
  | Companies
  | Code
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: src/lib/query.ts
// Variable: aboutPageQuery
// Query: *[_type == "about-page"][0] {    _id,    heroMonoLabel,    location,    title,      content[]{    ...,    markDefs[]{      ...,      _type == "internalLink" => {        ...,          "href": "/" + @.reference->_type + "/" + @.reference->slug.current,      },      _type == "externalLink" => {        ...,        "href": url,      },    },    _type == "image" => {      ...,      "url": asset->url,      "alt": alt,      "maxWidth": coalesce(maxWidth, "full"),    },    _type == "skillBadges" => {      ...,      skills[]->{          _id,  title,  url,  "logoLight": logoLight.asset->url,  "logoDark": logoDark.asset->url,      }    }  },    "image": {      "url": image.asset->url,      "alt": image.alt,    },    educationMonoLabel,    educationSectionTitle,    educationSectionDescription,    education[]{      "image": {        "url": image.asset->url,        "alt": image.alt,      },      degree,      university,      dateRange,      description,    },    skillsMonoLabel,    skillsSectionTitle,    skillsSectionDescription,    skillCategories[]{      categoryTitle,      skills[]->{          _id,  title,  url,  "logoLight": logoLight.asset->url,  "logoDark": logoDark.asset->url,      }    }  }
export type AboutPageQueryResult = {
  _id: string;
  heroMonoLabel: string;
  location: string;
  title: string;
  content: Array<
    | {
        children?: Array<
          | {
              language:
                | "csharp"
                | "css"
                | "go"
                | "groq"
                | "html"
                | "java"
                | "javascript"
                | "json"
                | "jsx"
                | "markdown"
                | "mysql"
                | "php"
                | "python"
                | "ruby"
                | "sh"
                | "sql"
                | "text"
                | "tsx"
                | "typescript"
                | "xml"
                | "yaml";
              code: string;
              _type: "customCode";
              _key: string;
            }
          | {
              body: string;
              _type: "latex";
              _key: string;
            }
          | {
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }
        >;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              url?: string;
              _type: "externalLink";
              _key: string;
              href: string | null;
            }
          | {
              reference:
                | AwardsReference
                | BlogsReference
                | ExperiencesReference
                | ProjectsReference;
              _type: "internalLink";
              _key: string;
              href: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
        markDefs: null;
      }
    | {
        contributors: Array<{
          profileUrl: string;
          _type: "contributorProfile";
          _key: string;
        }>;
        _type: "contributors";
        _key: string;
        markDefs: null;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        maxWidth:
          | "full"
          | "max-w-2xl"
          | "max-w-2xs"
          | "max-w-3xl"
          | "max-w-3xs"
          | "max-w-lg"
          | "max-w-md"
          | "max-w-sm"
          | "max-w-xl"
          | "max-w-xs";
        caption: boolean;
        _type: "image";
        _key: string;
        markDefs: null;
        url: string | null;
      }
    | {
        body: string;
        _type: "latex";
        _key: string;
        markDefs: null;
      }
    | {
        skills: Array<{
          _id: string;
          title: string;
          url: string;
          logoLight: string | null;
          logoDark: string | null;
        }>;
        _type: "skillBadges";
        _key: string;
        markDefs: null;
      }
  >;
  image: {
    url: string | null;
    alt: string;
  };
  educationMonoLabel: string;
  educationSectionTitle: string;
  educationSectionDescription: string;
  education: Array<{
    image: {
      url: string | null;
      alt: string;
    };
    degree: string;
    university: string;
    dateRange: {
      startDate: string;
      endDate?: string;
    };
    description: string;
  }>;
  skillsMonoLabel: string;
  skillsSectionTitle: string;
  skillsSectionDescription: string;
  skillCategories: Array<{
    categoryTitle: string;
    skills: Array<{
      _id: string;
      title: string;
      url: string;
      logoLight: string | null;
      logoDark: string | null;
    }>;
  }>;
} | null;

// Source: src/lib/query.ts
// Variable: projectsPageQuery
// Query: *[_type == "projects-page"][0] {    _id,    monoLabel,    detailMonoLabel,    title,    description,  }
export type ProjectsPageQueryResult = {
  _id: string;
  monoLabel: string;
  detailMonoLabel: string;
  title: string;
  description: string;
} | null;

// Source: src/lib/query.ts
// Variable: allProjectsQuery
// Query: *[_type == "projects"] | order(dateRange.startDate desc) {    _id,    "image": {      "url": image.asset->url,      "alt": image.alt,    },    title,    slug,    description,    dateRange,    repositoryLinks,    deploymentLinks,  }
export type AllProjectsQueryResult = Array<{
  _id: string;
  image: {
    url: string | null;
    alt: string;
  };
  title: string;
  slug: Slug;
  description: string;
  dateRange: {
    startDate: string;
    endDate?: string;
  };
  repositoryLinks: Array<{
    label: string;
    url: string;
    _type: "repositoryLink";
    _key: string;
  }> | null;
  deploymentLinks: Array<{
    label: string;
    url: string;
    _type: "deploymentLink";
    _key: string;
  }> | null;
}>;

// Source: src/lib/query.ts
// Variable: projectDetailQuery
// Query: *[_type == "projects" && slug.current == $slug][0] {    _id,    "image": {      "url": image.asset->url,      "alt": image.alt,    },    title,    slug,    description,    dateRange,    repositoryLinks,    deploymentLinks,      content[]{    ...,    markDefs[]{      ...,      _type == "internalLink" => {        ...,          "href": "/" + @.reference->_type + "/" + @.reference->slug.current,      },      _type == "externalLink" => {        ...,        "href": url,      },    },    _type == "image" => {      ...,      "url": asset->url,      "alt": alt,      "maxWidth": coalesce(maxWidth, "full"),    },    _type == "skillBadges" => {      ...,      skills[]->{          _id,  title,  url,  "logoLight": logoLight.asset->url,  "logoDark": logoDark.asset->url,      }    }  },    "detailMonoLabel": *[_type == "projects-page"][0].detailMonoLabel,    "previous": *[_type == "projects" && dateRange.startDate > ^.dateRange.startDate] | order(dateRange.startDate) [0] {      _id,      title,      slug,      description,      dateRange    },    "next": *[_type == "projects" && dateRange.startDate < ^.dateRange.startDate] | order(dateRange.startDate desc) [0] {      _id,      title,      slug,      description,      dateRange    },  }
export type ProjectDetailQueryResult = {
  _id: string;
  image: {
    url: string | null;
    alt: string;
  };
  title: string;
  slug: Slug;
  description: string;
  dateRange: {
    startDate: string;
    endDate?: string;
  };
  repositoryLinks: Array<{
    label: string;
    url: string;
    _type: "repositoryLink";
    _key: string;
  }> | null;
  deploymentLinks: Array<{
    label: string;
    url: string;
    _type: "deploymentLink";
    _key: string;
  }> | null;
  content: Array<
    | {
        children?: Array<
          | {
              language:
                | "csharp"
                | "css"
                | "go"
                | "groq"
                | "html"
                | "java"
                | "javascript"
                | "json"
                | "jsx"
                | "markdown"
                | "mysql"
                | "php"
                | "python"
                | "ruby"
                | "sh"
                | "sql"
                | "text"
                | "tsx"
                | "typescript"
                | "xml"
                | "yaml";
              code: string;
              _type: "customCode";
              _key: string;
            }
          | {
              body: string;
              _type: "latex";
              _key: string;
            }
          | {
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }
        >;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              url?: string;
              _type: "externalLink";
              _key: string;
              href: string | null;
            }
          | {
              reference:
                | AwardsReference
                | BlogsReference
                | ExperiencesReference
                | ProjectsReference;
              _type: "internalLink";
              _key: string;
              href: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
        markDefs: null;
      }
    | {
        contributors: Array<{
          profileUrl: string;
          _type: "contributorProfile";
          _key: string;
        }>;
        _type: "contributors";
        _key: string;
        markDefs: null;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        maxWidth:
          | "full"
          | "max-w-2xl"
          | "max-w-2xs"
          | "max-w-3xl"
          | "max-w-3xs"
          | "max-w-lg"
          | "max-w-md"
          | "max-w-sm"
          | "max-w-xl"
          | "max-w-xs";
        caption: boolean;
        _type: "image";
        _key: string;
        markDefs: null;
        url: string | null;
      }
    | {
        body: string;
        _type: "latex";
        _key: string;
        markDefs: null;
      }
    | {
        skills: Array<{
          _id: string;
          title: string;
          url: string;
          logoLight: string | null;
          logoDark: string | null;
        }>;
        _type: "skillBadges";
        _key: string;
        markDefs: null;
      }
  >;
  detailMonoLabel: string | null;
  previous: {
    _id: string;
    title: string;
    slug: Slug;
    description: string;
    dateRange: {
      startDate: string;
      endDate?: string;
    };
  } | null;
  next: {
    _id: string;
    title: string;
    slug: Slug;
    description: string;
    dateRange: {
      startDate: string;
      endDate?: string;
    };
  } | null;
} | null;

// Source: src/lib/query.ts
// Variable: experiencePageQuery
// Query: *[_type == "experiences-page"][0] {    _id,    monoLabel,    detailMonoLabel,    title,    description,  }
export type ExperiencePageQueryResult = {
  _id: string;
  monoLabel: string;
  detailMonoLabel: string;
  title: string;
  description: string;
} | null;

// Source: src/lib/query.ts
// Variable: allExperienceCompaniesQuery
// Query: *[    _type == "companies" &&    count(*[_type == "experiences" && defined(company._ref) && company._ref == ^._id && defined(slug.current)]) > 0  ] {    _id,    "image": {      "url": image.asset->url,      "alt": image.alt    },    "company": name,    "companySummary": summary,    "latestRoleStartDate": *[_type == "experiences" && defined(company._ref) && company._ref == ^._id && defined(slug.current)] | order(dateRange.startDate desc, slug.current asc)[0].dateRange.startDate,    "roles": *[_type == "experiences" && defined(company._ref) && company._ref == ^._id && defined(slug.current)] | order(dateRange.startDate desc, slug.current asc) {      _id,      _key,      title,      slug,      employmentType,      dateRange,      location,      repositoryLinks,      deploymentLinks,    },  }  | order(latestRoleStartDate desc, company asc)
export type AllExperienceCompaniesQueryResult = Array<{
  _id: string;
  image: {
    url: string | null;
    alt: string;
  };
  company: string;
  companySummary: string;
  latestRoleStartDate: string | null;
  roles: Array<{
    _id: string;
    _key: null;
    title: string;
    slug: Slug;
    employmentType:
      | "Contract"
      | "Full-time"
      | "Internship"
      | "Part-time"
      | null;
    dateRange: {
      startDate: string;
      endDate?: string;
    };
    location: string | null;
    repositoryLinks: Array<{
      label: string;
      url: string;
      _type: "repositoryLink";
      _key: string;
    }> | null;
    deploymentLinks: Array<{
      label: string;
      url: string;
      _type: "deploymentLink";
      _key: string;
    }> | null;
  }>;
}>;

// Source: src/lib/query.ts
// Variable: experienceRoleDetailQuery
// Query: *[_type == "experiences" && slug.current == $slug && defined(company._ref)][0] {    _id,    title,    slug,    employmentType,    dateRange,    location,    repositoryLinks,    deploymentLinks,      content[]{    ...,    markDefs[]{      ...,      _type == "internalLink" => {        ...,          "href": "/" + @.reference->_type + "/" + @.reference->slug.current,      },      _type == "externalLink" => {        ...,        "href": url,      },    },    _type == "image" => {      ...,      "url": asset->url,      "alt": alt,      "maxWidth": coalesce(maxWidth, "full"),    },    _type == "skillBadges" => {      ...,      skills[]->{          _id,  title,  url,  "logoLight": logoLight.asset->url,  "logoDark": logoDark.asset->url,      }    }  },    "company": {      "name": company->name,      "summary": company->summary,      "image": {        "url": company->image.asset->url,        "alt": company->image.alt      }    },    "detailMonoLabel": *[_type == "experiences-page"][0].detailMonoLabel  }
export type ExperienceRoleDetailQueryResult = {
  _id: string;
  title: string;
  slug: Slug;
  employmentType: "Contract" | "Full-time" | "Internship" | "Part-time" | null;
  dateRange: {
    startDate: string;
    endDate?: string;
  };
  location: string | null;
  repositoryLinks: Array<{
    label: string;
    url: string;
    _type: "repositoryLink";
    _key: string;
  }> | null;
  deploymentLinks: Array<{
    label: string;
    url: string;
    _type: "deploymentLink";
    _key: string;
  }> | null;
  content: Array<
    | {
        children?: Array<
          | {
              language:
                | "csharp"
                | "css"
                | "go"
                | "groq"
                | "html"
                | "java"
                | "javascript"
                | "json"
                | "jsx"
                | "markdown"
                | "mysql"
                | "php"
                | "python"
                | "ruby"
                | "sh"
                | "sql"
                | "text"
                | "tsx"
                | "typescript"
                | "xml"
                | "yaml";
              code: string;
              _type: "customCode";
              _key: string;
            }
          | {
              body: string;
              _type: "latex";
              _key: string;
            }
          | {
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }
        >;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              url?: string;
              _type: "externalLink";
              _key: string;
              href: string | null;
            }
          | {
              reference:
                | AwardsReference
                | BlogsReference
                | ExperiencesReference
                | ProjectsReference;
              _type: "internalLink";
              _key: string;
              href: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
        markDefs: null;
      }
    | {
        contributors: Array<{
          profileUrl: string;
          _type: "contributorProfile";
          _key: string;
        }>;
        _type: "contributors";
        _key: string;
        markDefs: null;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        maxWidth:
          | "full"
          | "max-w-2xl"
          | "max-w-2xs"
          | "max-w-3xl"
          | "max-w-3xs"
          | "max-w-lg"
          | "max-w-md"
          | "max-w-sm"
          | "max-w-xl"
          | "max-w-xs";
        caption: boolean;
        _type: "image";
        _key: string;
        markDefs: null;
        url: string | null;
      }
    | {
        body: string;
        _type: "latex";
        _key: string;
        markDefs: null;
      }
    | {
        skills: Array<{
          _id: string;
          title: string;
          url: string;
          logoLight: string | null;
          logoDark: string | null;
        }>;
        _type: "skillBadges";
        _key: string;
        markDefs: null;
      }
  >;
  company: {
    name: string;
    summary: string;
    image: {
      url: string | null;
      alt: string;
    };
  };
  detailMonoLabel: string | null;
} | null;

// Source: src/lib/query.ts
// Variable: awardsPageQuery
// Query: *[_type == "awards-page"][0] {    _id,    monoLabel,    detailMonoLabel,    title,    description,  }
export type AwardsPageQueryResult = {
  _id: string;
  monoLabel: string;
  detailMonoLabel: string;
  title: string;
  description: string;
} | null;

// Source: src/lib/query.ts
// Variable: allAwardsQuery
// Query: *[_type == "awards"] | order(date desc) {    _id,    "image": {      "url": image.asset->url,      "alt": image.alt    },    title,    slug,    description,    issuer,    date,  }
export type AllAwardsQueryResult = Array<{
  _id: string;
  image: {
    url: string | null;
    alt: string;
  };
  title: string;
  slug: Slug;
  description: string;
  issuer: string;
  date: string;
}>;

// Source: src/lib/query.ts
// Variable: awardDetailQuery
// Query: *[_type == "awards" && slug.current == $slug][0] {    _id,    "image": {      "url": image.asset->url,      "alt": image.alt    },    title,    slug,    description,    issuer,    date,      content[]{    ...,    markDefs[]{      ...,      _type == "internalLink" => {        ...,          "href": "/" + @.reference->_type + "/" + @.reference->slug.current,      },      _type == "externalLink" => {        ...,        "href": url,      },    },    _type == "image" => {      ...,      "url": asset->url,      "alt": alt,      "maxWidth": coalesce(maxWidth, "full"),    },    _type == "skillBadges" => {      ...,      skills[]->{          _id,  title,  url,  "logoLight": logoLight.asset->url,  "logoDark": logoDark.asset->url,      }    }  },    "detailMonoLabel": *[_type == "awards-page"][0].detailMonoLabel,    "previous": *[_type == "awards" && date > ^.date] | order(date) [0] {      _id,      title,      slug,      description,      issuer,      date    },    "next": *[_type == "awards" && date < ^.date] | order(date desc) [0] {      _id,      title,      slug,      description,      issuer,      date    },  }
export type AwardDetailQueryResult = {
  _id: string;
  image: {
    url: string | null;
    alt: string;
  };
  title: string;
  slug: Slug;
  description: string;
  issuer: string;
  date: string;
  content: Array<
    | {
        children?: Array<
          | {
              language:
                | "csharp"
                | "css"
                | "go"
                | "groq"
                | "html"
                | "java"
                | "javascript"
                | "json"
                | "jsx"
                | "markdown"
                | "mysql"
                | "php"
                | "python"
                | "ruby"
                | "sh"
                | "sql"
                | "text"
                | "tsx"
                | "typescript"
                | "xml"
                | "yaml";
              code: string;
              _type: "customCode";
              _key: string;
            }
          | {
              body: string;
              _type: "latex";
              _key: string;
            }
          | {
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }
        >;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              url?: string;
              _type: "externalLink";
              _key: string;
              href: string | null;
            }
          | {
              reference:
                | AwardsReference
                | BlogsReference
                | ExperiencesReference
                | ProjectsReference;
              _type: "internalLink";
              _key: string;
              href: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
        markDefs: null;
      }
    | {
        contributors: Array<{
          profileUrl: string;
          _type: "contributorProfile";
          _key: string;
        }>;
        _type: "contributors";
        _key: string;
        markDefs: null;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        maxWidth:
          | "full"
          | "max-w-2xl"
          | "max-w-2xs"
          | "max-w-3xl"
          | "max-w-3xs"
          | "max-w-lg"
          | "max-w-md"
          | "max-w-sm"
          | "max-w-xl"
          | "max-w-xs";
        caption: boolean;
        _type: "image";
        _key: string;
        markDefs: null;
        url: string | null;
      }
    | {
        body: string;
        _type: "latex";
        _key: string;
        markDefs: null;
      }
    | {
        skills: Array<{
          _id: string;
          title: string;
          url: string;
          logoLight: string | null;
          logoDark: string | null;
        }>;
        _type: "skillBadges";
        _key: string;
        markDefs: null;
      }
  >;
  detailMonoLabel: string | null;
  previous: {
    _id: string;
    title: string;
    slug: Slug;
    description: string;
    issuer: string;
    date: string;
  } | null;
  next: {
    _id: string;
    title: string;
    slug: Slug;
    description: string;
    issuer: string;
    date: string;
  } | null;
} | null;

// Source: src/lib/query.ts
// Variable: socialsQuery
// Query: *[_type == "socials"][0] {    _id,    socialLinks[]{      name,      url,      "iconLight": {        "url": iconLight.asset->url,        "alt": iconLight.alt,      },      "iconDark": {        "url": iconDark.asset->url,        "alt": iconDark.alt,      }    }  }
export type SocialsQueryResult = {
  _id: string;
  socialLinks: Array<{
    name: string;
    url: string;
    iconLight: {
      url: string | null;
      alt: string;
    };
    iconDark: {
      url: string | null;
      alt: string;
    };
  }> | null;
} | null;

// Source: src/lib/query.ts
// Variable: blogPageQuery
// Query: *[_type == "blogs-page"][0] {    _id,    monoLabel,    detailMonoLabel,    title,    description,  }
export type BlogPageQueryResult = {
  _id: string;
  monoLabel: string;
  detailMonoLabel: string;
  title: string;
  description: string;
} | null;

// Source: src/lib/query.ts
// Variable: allBlogsQuery
// Query: *[_type == "blogs"] | order(date desc) {    _id,    "image": {      "url": image.asset->url,      "alt": image.alt,    },    title,    slug,    description,    date,  }
export type AllBlogsQueryResult = Array<{
  _id: string;
  image: {
    url: string | null;
    alt: string;
  };
  title: string;
  slug: Slug;
  description: string;
  date: string;
}>;

// Source: src/lib/query.ts
// Variable: blogDetailQuery
// Query: *[_type == "blogs" && slug.current == $slug][0] {    _id,    "image": {      "url": image.asset->url,      "alt": image.alt,    },    title,    slug,    description,    date,      content[]{    ...,    markDefs[]{      ...,      _type == "internalLink" => {        ...,          "href": "/" + @.reference->_type + "/" + @.reference->slug.current,      },      _type == "externalLink" => {        ...,        "href": url,      },    },    _type == "image" => {      ...,      "url": asset->url,      "alt": alt,      "maxWidth": coalesce(maxWidth, "full"),    },    _type == "skillBadges" => {      ...,      skills[]->{          _id,  title,  url,  "logoLight": logoLight.asset->url,  "logoDark": logoDark.asset->url,      }    }  },    "detailMonoLabel": *[_type == "blogs-page"][0].detailMonoLabel,    "authorName": *[_type == "about-page"][0].title,    "authorImage": {      "url": *[_type == "about-page"][0].image.asset->url,      "alt": *[_type == "about-page"][0].image.alt,    },    "previous": *[_type == "blogs" && date > ^.date] | order(date) [0] {      _id,      title,      slug,      description,      date    },    "next": *[_type == "blogs" && date < ^.date] | order(date desc) [0] {      _id,      title,      slug,      description,      date    },  }
export type BlogDetailQueryResult = {
  _id: string;
  image: {
    url: string | null;
    alt: string;
  };
  title: string;
  slug: Slug;
  description: string;
  date: string;
  content: Array<
    | {
        children?: Array<
          | {
              language:
                | "csharp"
                | "css"
                | "go"
                | "groq"
                | "html"
                | "java"
                | "javascript"
                | "json"
                | "jsx"
                | "markdown"
                | "mysql"
                | "php"
                | "python"
                | "ruby"
                | "sh"
                | "sql"
                | "text"
                | "tsx"
                | "typescript"
                | "xml"
                | "yaml";
              code: string;
              _type: "customCode";
              _key: string;
            }
          | {
              body: string;
              _type: "latex";
              _key: string;
            }
          | {
              marks?: Array<string>;
              text?: string;
              _type: "span";
              _key: string;
            }
        >;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs: Array<
          | {
              url?: string;
              _type: "externalLink";
              _key: string;
              href: string | null;
            }
          | {
              reference:
                | AwardsReference
                | BlogsReference
                | ExperiencesReference
                | ProjectsReference;
              _type: "internalLink";
              _key: string;
              href: string;
            }
        > | null;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
        markDefs: null;
      }
    | {
        contributors: Array<{
          profileUrl: string;
          _type: "contributorProfile";
          _key: string;
        }>;
        _type: "contributors";
        _key: string;
        markDefs: null;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        maxWidth:
          | "full"
          | "max-w-2xl"
          | "max-w-2xs"
          | "max-w-3xl"
          | "max-w-3xs"
          | "max-w-lg"
          | "max-w-md"
          | "max-w-sm"
          | "max-w-xl"
          | "max-w-xs";
        caption: boolean;
        _type: "image";
        _key: string;
        markDefs: null;
        url: string | null;
      }
    | {
        body: string;
        _type: "latex";
        _key: string;
        markDefs: null;
      }
    | {
        skills: Array<{
          _id: string;
          title: string;
          url: string;
          logoLight: string | null;
          logoDark: string | null;
        }>;
        _type: "skillBadges";
        _key: string;
        markDefs: null;
      }
  >;
  detailMonoLabel: string | null;
  authorName: string | null;
  authorImage: {
    url: string | null;
    alt: string | null;
  };
  previous: {
    _id: string;
    title: string;
    slug: Slug;
    description: string;
    date: string;
  } | null;
  next: {
    _id: string;
    title: string;
    slug: Slug;
    description: string;
    date: string;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "about-page"][0] {\n    _id,\n    heroMonoLabel,\n    location,\n    title,\n    \n  content[]{\n    ...,\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        ...,\n        \n  "href": "/" + @.reference->_type + "/" + @.reference->slug.current,\n\n      },\n      _type == "externalLink" => {\n        ...,\n        "href": url,\n      },\n    },\n    _type == "image" => {\n      ...,\n      "url": asset->url,\n      "alt": alt,\n      "maxWidth": coalesce(maxWidth, "full"),\n    },\n    _type == "skillBadges" => {\n      ...,\n      skills[]->{\n        \n  _id,\n  title,\n  url,\n  "logoLight": logoLight.asset->url,\n  "logoDark": logoDark.asset->url,\n\n      }\n    }\n  },\n\n    "image": {\n      "url": image.asset->url,\n      "alt": image.alt,\n    },\n    educationMonoLabel,\n    educationSectionTitle,\n    educationSectionDescription,\n    education[]{\n      "image": {\n        "url": image.asset->url,\n        "alt": image.alt,\n      },\n      degree,\n      university,\n      dateRange,\n      description,\n    },\n    skillsMonoLabel,\n    skillsSectionTitle,\n    skillsSectionDescription,\n    skillCategories[]{\n      categoryTitle,\n      skills[]->{\n        \n  _id,\n  title,\n  url,\n  "logoLight": logoLight.asset->url,\n  "logoDark": logoDark.asset->url,\n\n      }\n    }\n  }\n': AboutPageQueryResult;
    '\n  *[_type == "projects-page"][0] {\n    _id,\n    monoLabel,\n    detailMonoLabel,\n    title,\n    description,\n  }\n': ProjectsPageQueryResult;
    '\n  *[_type == "projects"] | order(dateRange.startDate desc) {\n    _id,\n    "image": {\n      "url": image.asset->url,\n      "alt": image.alt,\n    },\n    title,\n    slug,\n    description,\n    dateRange,\n    repositoryLinks,\n    deploymentLinks,\n  }\n': AllProjectsQueryResult;
    '\n  *[_type == "projects" && slug.current == $slug][0] {\n    _id,\n    "image": {\n      "url": image.asset->url,\n      "alt": image.alt,\n    },\n    title,\n    slug,\n    description,\n    dateRange,\n    repositoryLinks,\n    deploymentLinks,\n    \n  content[]{\n    ...,\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        ...,\n        \n  "href": "/" + @.reference->_type + "/" + @.reference->slug.current,\n\n      },\n      _type == "externalLink" => {\n        ...,\n        "href": url,\n      },\n    },\n    _type == "image" => {\n      ...,\n      "url": asset->url,\n      "alt": alt,\n      "maxWidth": coalesce(maxWidth, "full"),\n    },\n    _type == "skillBadges" => {\n      ...,\n      skills[]->{\n        \n  _id,\n  title,\n  url,\n  "logoLight": logoLight.asset->url,\n  "logoDark": logoDark.asset->url,\n\n      }\n    }\n  },\n\n    "detailMonoLabel": *[_type == "projects-page"][0].detailMonoLabel,\n    "previous": *[_type == "projects" && dateRange.startDate > ^.dateRange.startDate] | order(dateRange.startDate) [0] {\n      _id,\n      title,\n      slug,\n      description,\n      dateRange\n    },\n    "next": *[_type == "projects" && dateRange.startDate < ^.dateRange.startDate] | order(dateRange.startDate desc) [0] {\n      _id,\n      title,\n      slug,\n      description,\n      dateRange\n    },\n  }\n': ProjectDetailQueryResult;
    '\n  *[_type == "experiences-page"][0] {\n    _id,\n    monoLabel,\n    detailMonoLabel,\n    title,\n    description,\n  }\n': ExperiencePageQueryResult;
    '\n  *[\n    _type == "companies" &&\n    count(*[_type == "experiences" && defined(company._ref) && company._ref == ^._id && defined(slug.current)]) > 0\n  ] {\n    _id,\n    "image": {\n      "url": image.asset->url,\n      "alt": image.alt\n    },\n    "company": name,\n    "companySummary": summary,\n    "latestRoleStartDate": *[_type == "experiences" && defined(company._ref) && company._ref == ^._id && defined(slug.current)] | order(dateRange.startDate desc, slug.current asc)[0].dateRange.startDate,\n    "roles": *[_type == "experiences" && defined(company._ref) && company._ref == ^._id && defined(slug.current)] | order(dateRange.startDate desc, slug.current asc) {\n      _id,\n      _key,\n      title,\n      slug,\n      employmentType,\n      dateRange,\n      location,\n      repositoryLinks,\n      deploymentLinks,\n    },\n  }\n  | order(latestRoleStartDate desc, company asc)\n': AllExperienceCompaniesQueryResult;
    '\n  *[_type == "experiences" && slug.current == $slug && defined(company._ref)][0] {\n    _id,\n    title,\n    slug,\n    employmentType,\n    dateRange,\n    location,\n    repositoryLinks,\n    deploymentLinks,\n    \n  content[]{\n    ...,\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        ...,\n        \n  "href": "/" + @.reference->_type + "/" + @.reference->slug.current,\n\n      },\n      _type == "externalLink" => {\n        ...,\n        "href": url,\n      },\n    },\n    _type == "image" => {\n      ...,\n      "url": asset->url,\n      "alt": alt,\n      "maxWidth": coalesce(maxWidth, "full"),\n    },\n    _type == "skillBadges" => {\n      ...,\n      skills[]->{\n        \n  _id,\n  title,\n  url,\n  "logoLight": logoLight.asset->url,\n  "logoDark": logoDark.asset->url,\n\n      }\n    }\n  },\n\n    "company": {\n      "name": company->name,\n      "summary": company->summary,\n      "image": {\n        "url": company->image.asset->url,\n        "alt": company->image.alt\n      }\n    },\n    "detailMonoLabel": *[_type == "experiences-page"][0].detailMonoLabel\n  }\n': ExperienceRoleDetailQueryResult;
    '\n  *[_type == "awards-page"][0] {\n    _id,\n    monoLabel,\n    detailMonoLabel,\n    title,\n    description,\n  }\n': AwardsPageQueryResult;
    '\n  *[_type == "awards"] | order(date desc) {\n    _id,\n    "image": {\n      "url": image.asset->url,\n      "alt": image.alt\n    },\n    title,\n    slug,\n    description,\n    issuer,\n    date,\n  }\n': AllAwardsQueryResult;
    '\n  *[_type == "awards" && slug.current == $slug][0] {\n    _id,\n    "image": {\n      "url": image.asset->url,\n      "alt": image.alt\n    },\n    title,\n    slug,\n    description,\n    issuer,\n    date,\n    \n  content[]{\n    ...,\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        ...,\n        \n  "href": "/" + @.reference->_type + "/" + @.reference->slug.current,\n\n      },\n      _type == "externalLink" => {\n        ...,\n        "href": url,\n      },\n    },\n    _type == "image" => {\n      ...,\n      "url": asset->url,\n      "alt": alt,\n      "maxWidth": coalesce(maxWidth, "full"),\n    },\n    _type == "skillBadges" => {\n      ...,\n      skills[]->{\n        \n  _id,\n  title,\n  url,\n  "logoLight": logoLight.asset->url,\n  "logoDark": logoDark.asset->url,\n\n      }\n    }\n  },\n\n    "detailMonoLabel": *[_type == "awards-page"][0].detailMonoLabel,\n    "previous": *[_type == "awards" && date > ^.date] | order(date) [0] {\n      _id,\n      title,\n      slug,\n      description,\n      issuer,\n      date\n    },\n    "next": *[_type == "awards" && date < ^.date] | order(date desc) [0] {\n      _id,\n      title,\n      slug,\n      description,\n      issuer,\n      date\n    },\n  }\n': AwardDetailQueryResult;
    '\n  *[_type == "socials"][0] {\n    _id,\n    socialLinks[]{\n      name,\n      url,\n      "iconLight": {\n        "url": iconLight.asset->url,\n        "alt": iconLight.alt,\n      },\n      "iconDark": {\n        "url": iconDark.asset->url,\n        "alt": iconDark.alt,\n      }\n    }\n  }\n': SocialsQueryResult;
    '\n  *[_type == "blogs-page"][0] {\n    _id,\n    monoLabel,\n    detailMonoLabel,\n    title,\n    description,\n  }\n': BlogPageQueryResult;
    '\n  *[_type == "blogs"] | order(date desc) {\n    _id,\n    "image": {\n      "url": image.asset->url,\n      "alt": image.alt,\n    },\n    title,\n    slug,\n    description,\n    date,\n  }\n': AllBlogsQueryResult;
    '\n  *[_type == "blogs" && slug.current == $slug][0] {\n    _id,\n    "image": {\n      "url": image.asset->url,\n      "alt": image.alt,\n    },\n    title,\n    slug,\n    description,\n    date,\n    \n  content[]{\n    ...,\n    markDefs[]{\n      ...,\n      _type == "internalLink" => {\n        ...,\n        \n  "href": "/" + @.reference->_type + "/" + @.reference->slug.current,\n\n      },\n      _type == "externalLink" => {\n        ...,\n        "href": url,\n      },\n    },\n    _type == "image" => {\n      ...,\n      "url": asset->url,\n      "alt": alt,\n      "maxWidth": coalesce(maxWidth, "full"),\n    },\n    _type == "skillBadges" => {\n      ...,\n      skills[]->{\n        \n  _id,\n  title,\n  url,\n  "logoLight": logoLight.asset->url,\n  "logoDark": logoDark.asset->url,\n\n      }\n    }\n  },\n\n    "detailMonoLabel": *[_type == "blogs-page"][0].detailMonoLabel,\n    "authorName": *[_type == "about-page"][0].title,\n    "authorImage": {\n      "url": *[_type == "about-page"][0].image.asset->url,\n      "alt": *[_type == "about-page"][0].image.alt,\n    },\n    "previous": *[_type == "blogs" && date > ^.date] | order(date) [0] {\n      _id,\n      title,\n      slug,\n      description,\n      date\n    },\n    "next": *[_type == "blogs" && date < ^.date] | order(date desc) [0] {\n      _id,\n      title,\n      slug,\n      description,\n      date\n    },\n  }\n': BlogDetailQueryResult;
  }
}
