name: ESLint & Prettier Formatter

on: push

jobs:
  run-formatter:
    name: Run Formatter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Formatter
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          eslint: true
          prettier: true
