name: Linter & Formatter

on: push

jobs:
  run-formatter:
    name: Run Formatter
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Formatter
        run: npm run lint

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '🔨 Format code'
          commit_options: '--no-verify'
          branch: ${{ github.ref }}
